### ISSUE TITLE
pyez breaking nornir inventory path

### ISSUE THREAD

**Issue by cpmarvin** [cpmarvin/lnetd#2]
Open for tracking.

Nornir scripts are failling with the following error. 

Failed to import 'nornir.plugins.inventory.simple.SimpleInventory'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/deserializer/configuration.py", line 217, in _resolve_import_from_string
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nornir.plugins.inventory.simple'; 'nornir.plugins.inventory' is not a package

**Comment by cpmarvin** [comment]
fix in cc3bcddb36b56ef39395eb6f769a8f30db981d8d
